items:
- name: Kubernetes
  include: { mode: link, path: orchestrated/toc_p.yaml }
- name: VM / Baremetal
  href: manual/deploy-ydb-on-premises.md
- name: Configuration
  href: configuration/config.md
  # - name: Production checklist
  #  href: ../deploy/production_checklist.md
