name: PR check
on: 
  pull_request_target:
    branches:
      - 'main'
    paths-ignore:
      - 'ydb/docs/**'
      
jobs:
  build_and_test:
    uses: ./.github/workflows/build_and_test_ondemand.yml
    if: github.event.review.state == 'approved'
    with:
      test_label_regexp: '(SMALL|MEDIUM)'
    secrets: inherit
